
var i;

var mapaTraducoes = {
  "US":"Estados Unidos da América",
  "USA":"Estados Unidos da América",
  "United States of America":"Estados Unidos da América",
  "Italy":"Itália",
  "China":"China",
  "Spain":"Espanha",
  "Germany":"Alemanha",
  "France":"França",
  "Iran":"Irã",
  "Czech Republic":"República Tcheca",
  "Macedonia, Republic of":"Macedônia",
  "Taiwan, Republic of China":"Taiwan",
  "Palestinian Territory":"Palestina",
  "Côte d'Ivoire":"Costa do Marfim",
  "Venezuela (Bolivarian Republic)":"Venezuela",
  "Tanzania, United Republic of":"Tanzânia",
  "Syrian Arab Republic (Syria)":"Síria",
  "Holy See (Vatican City State)":"Vaticano",
  "Iran, Islamic Republic of":"Irã (Republica Islâmica do Irã)",
  "United Kingdom":"Reino Unido",
  "Switzerland":"Suíça",
  "Turkey":"Peru",
  "Belgium":"Bélgica",
  "Netherlands":"Países Baixos / Holanda",
  "Austria":"Áustria",
  "Korea (South)":"Coréia do Sul",
  "Korea, South":"Coréia do Sul",
  "Republic of Korea":"República da Coreia",
  "South Korea":"Coréia do Sul",
  "Canada":"Canadá",
  "Portugal":"Portugal",
  "Brazil":"Brasil",
  "Israel":"Israel",
  "Sweden":"Suécia",
  "Norway":"Noruega",
  "Australia":"Austrália",
  "Czechia":"República Tcheca",
  "Ireland":"Irlanda",
  "Denmark":"Dinamarca",
  "Chile":"Chile",
  "Malaysia":"Malásia",
  "Russia":"Rússia",
  "Russian Federation":"Federação Russa",
  "Ecuador":"Equador",
  "Poland":"Polônia",
  "Romania":"Romênia",
  "Japan":"Japão",
  "Luxembourg":"Luxemburgo",
  "Philippines":"Filipinas",
  "Pakistan":"Paquistão",
  "India":"Índia",
  "Thailand":"Tailândia",
  "Saudi Arabia":"Arábia Saudita",
  "Indonesia":"Indonésia",
  "Finland":"Finlândia",
  "Greece":"Grécia",
  "South Africa":"África do Sul",
  "Peru":"Peru",
  "Panama":"Panamá",
  "Dominican Republic":"República Dominicana",
  "Iceland":"Islândia",
  "Mexico":"México",
  "Argentina":"Argentina",
  "Colombia":"Colômbia",
  "Serbia":"Sérvia",
  "Singapore":"Cingapura",
  "Croatia":"Croácia",
  "Algeria":"Argélia",
  "Slovenia":"Eslovênia",
  "Qatar":"Catar",
  "United Arab Emirates":"Emirados Árabes Unidos",
  "New Zealand":"Nova Zelândia",
  "Ukraine":"Ucrânia",
  "Egypt":"Egito",
  "Estonia":"Estônia",
  "Iraq":"Iraque",
  "Cruise Ship":"Cruzeiro",
  "Diamond Princess":"Diamond Princess (navio)",
  "Others":"Outras",
  "Morocco":"Marrocos",
  "Lithuania":"Lituânia",
  "Armenia":"Armênia",
  "Bahrain":"Bahrain",
  "Hungary":"Hungria",
  "Lebanon":"Líbano",
  "Bosnia and Herzegovina":"Bósnia e Herzegovina",
  "Latvia":"Letônia",
  "Moldova":"Moldova",
  "Tunisia":"Tunísia",
  "Bulgaria":"Bulgária",
  "Slovakia":"Eslováquia",
  "Andorra":"Andorra",
  "Kazakhstan":"Cazaquistão",
  "Costa Rica":"Costa Rica",
  "Azerbaijan":"Azerbaijão",
  "North Macedonia":"Macedônia do Norte",
  "Uruguay":"Uruguai",
  "Taiwan":"Taiwan",
  "Taiwan*":"Taiwan*",
  "Cyprus":"Chipre",
  "Kuwait":"Kuwait",
  "Burkina Faso":"Burkina Faso",
  "Jordan":"Jordânia",
  "Albania":"Albânia",
  "Afghanistan":"Afeganistão",
  "San Marino":"San Marino",
  "Cameroon":"Camarões",
  "Viet Nam":"Vietnã",
  "Vietnam":"Vietnã",
  "Cuba":"Cuba",
  "Oman":"Omã",
  "Ghana":"Gana",
  "Cote d'Ivoire":"Costa do Marfim",
  "Senegal":"Senegal",
  "Malta":"Malta",
  "Uzbekistan":"Uzbequistão",
  "Nigeria":"Nigéria",
  "Honduras":"Honduras",
  "Belarus":"Bielorrússia",
  "Mauritius":"Maurícia",
  "Sri Lanka":"Sri Lanka",
  "Venezuela":"Venezuela",
  "West Bank and Gaza":"Cisjordânia e Gaza",
  "Brunei":"Brunei",
  "Kosovo":"Kosovo",
  "Montenegro":"Montenegro",
  "Georgia":"Geórgia",
  "Bolivia":"Bolívia",
  "Hong Kong":"Hong Kong",
  "Kyrgyzstan":"Quirguistão",
  "Cambodia":"Camboja",
  "Congo (Kinshasa)":"Congo (Kinshasa)",
  "Trinidad and Tobago":"Trinidad e Tobago",
  "Rwanda":"Ruanda",
  "Kenya":"Quênia",
  "Paraguay":"Paraguai",
  "Niger":"Níger",
  "Liechtenstein":"Liechtenstein",
  "Madagascar":"Madagascar",
  "Guadeloupe":"Guadalupe",
  "Monaco":"Mônaco",
  "Bangladesh":"Bangladesh",
  "Reunion":"Reunião",
  "Guatemala":"Guatemala",
  "Barbados":"Barbados",
  "Jamaica":"Jamaica",
  "Uganda":"Uganda",
  "Martinique":"Martinica",
  "Togo":"Togo",
  "Zambia":"Zâmbia",
  "Djibouti":"Djibuti",
  "El Salvador":"El Salvador",
  "Mali":"Mali",
  "Guinea":"Guiné",
  "Ethiopia":"Etiópia",
  "Congo (Brazzaville)":"Congo (Brazzaville)",
  "Palestine":"Palestina",
  "Bahamas":"Bahamas",
  "Tanzania":"Tanzânia",
  "Guyana":"Guiana",
  "Maldives":"Maldivas",
  "French Guiana":"Guiana Francesa",
  "Gabon":"Gabão",
  "Burma":"Birmânia",
  "Haiti":"Haiti",
  "Equatorial Guinea":"Guiné Equatorial",
  "Eritrea":"Eritreia",
  "Mongolia":"Mongólia",
  "Namibia":"Namíbia",
  "Benin":"Benin",
  "Saint Lucia":"Santa Lúcia",
  "Dominica":"Dominica",
  "Mayotte":"Mayotte",
  "Grenada":"Granada",
  "Laos":"Laos",
  "Libya":"Líbia",
  "Macau":"Macau",
  "Mozambique":"Moçambique",
  "Seychelles":"Seychelles",
  "Suriname":"Suriname",
  "Syria":"Síria",
  "Eswatini":"Eswatini",
  "Guinea-Bissau":"Guiné-Bissau",
  "MS Zaandam":"MS Zaandam",
  "Angola":"Angola",
  "Saint Kitts and Nevis":"São Cristóvão e Nevis",
  "Zimbabwe":"Zimbábue",
  "Antigua and Barbuda":"Antígua e Barbuda",
  "Chad":"Chade",
  "Sudan":"Sudão",
  "Cabo Verde":"Cabo Verde",
  "Holy See":"Santa Sé",
  "Liberia":"Libéria",
  "Mauritania":"Mauritânia",
  "Fiji":"Fiji",
  "Nepal":"Nepal",
  "Nicaragua":"Nicarágua",
  "Somalia":"Somália",
  "Aruba":"Aruba",
  "Bahamas, The":"Bahamas",
  "Bhutan":"Butão",
  "Botswana":"Botsuana",
  "Gambia":"Gâmbia",
  "Belize":"Belize",
  "Central African Republic":"República Centro-Africana",
  "Faroe Islands":"Ilhas Faroe",
  "Saint Vincent and the Grenadines":"São Vicente e Granadinas",
  "Cayman Islands":"Ilhas Cayman",
  "Gambia, The":"Gâmbia",
  "Gibraltar":"Gibraltar",
  "Papua New Guinea":"Papua Nova Guiné",
  "Saint Barthelemy":"São Bartolomeu",
  "Timor-Leste":"Timor-Leste",
  "Cape Verde":"Cabo Verde",
  "Channel Islands":"Ilhas do Canal",
  "Vatican City":"Vaticano"
};

function indicateBad(x){
  if (x.innerHTML>0) {
    x.setAttribute("class", "valor valornovo plus bad");
    x.innerHTML = "+" + x.innerHTML;
  }
}

function indicateGood(y){
  if (y.innerHTML>0) {
    y.setAttribute("class", "valor novosrec plus good");
    // y.innerHTML = "+" + y.innerHTML;
  }
}

var paises = document.getElementsByClassName('country');
var rows = document.getElementsByName('rows');
var valores = document.getElementsByClassName('valor');
var newval = document.getElementsByClassName('valornovo');
var newrec = document.getElementsByClassName('novosrec');

for (i=0; i < rows.length; i++){

  // if (paises[i] == 'united kingdom') {
  //   document.getElementById("recovfield").innerHTML = "N/A";
  // }
  if (Object.keys(mapaTraducoes).indexOf(paises[i].innerHTML) > -1) {
     paises[i].innerHTML = mapaTraducoes[paises[i].innerHTML];
  }
  indicateBad(newval[i]);
  indicateGood(newrec[i]);
  // if (newval[i].innerHTML > 1){
  //   newval[i].setAttribute("class", "valor valornovo plus");
  //   newval[i].innerHTML = "+" + newval[i].innerHTML;
  // }


};
// document.getElementById('abc').innerHTML = data["Countries"][1]["Country"];
